package store

import (
	"database/sql"
	"fmt"
	"regexp"

	_ "github.com/duckdb/duckdb-go/v2"
)

type Store struct {
	db *sql.DB
}

const schema = `
CREATE TABLE IF NOT EXISTS votes (
    ts        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    survey_id VARCHAR   NOT NULL,
    answer    VARCHAR   NOT NULL,
    voter     VARCHAR   NOT NULL,
    PRIMARY KEY (survey_id, voter)
);
`

// tokenSafe restricts the Quack token to URL-safe base64 chars so we can
// interpolate it into SQL without escaping. The token is generated by the
// operator (base64 of /dev/urandom), so this is purely a defence-in-depth check.
var tokenSafe = regexp.MustCompile(`^[A-Za-z0-9+/=_-]+$`)

func Open(path, quackAddr, quackToken string) (*Store, error) {
	if !tokenSafe.MatchString(quackToken) {
		return nil, fmt.Errorf("SURVEY_QUACK_TOKEN must be URL-safe base64")
	}

	db, err := sql.Open("duckdb", path)
	if err != nil {
		return nil, err
	}
	// DuckDB has a single writer. Pin to one connection so writes and the
	// quack_serve call share the same session.
	db.SetMaxOpenConns(1)

	if _, err := db.Exec(schema); err != nil {
		return nil, fmt.Errorf("schema: %w", err)
	}

	if _, err := db.Exec(`INSTALL quack`); err != nil {
		return nil, fmt.Errorf("install quack: %w", err)
	}
	if _, err := db.Exec(`LOAD quack`); err != nil {
		return nil, fmt.Errorf("load quack: %w", err)
	}

	// quack_serve takes named args via `=>`. The Go driver doesn't bind named
	// params, so we interpolate after validating both inputs above.
	quackURI := fmt.Sprintf("quack:%s", quackAddr)
	serveSQL := fmt.Sprintf(
		"CALL quack_serve('%s', token => '%s', allow_other_hostname => true)",
		quackURI, quackToken,
	)
	if _, err := db.Exec(serveSQL); err != nil {
		return nil, fmt.Errorf("quack_serve: %w", err)
	}

	return &Store{db: db}, nil
}

func (s *Store) Close() error { return s.db.Close() }

func (s *Store) RecordVote(surveyID, answer, voter string) error {
	const q = `
		INSERT INTO votes (survey_id, answer, voter) VALUES (?, ?, ?)
		ON CONFLICT (survey_id, voter) DO UPDATE
		SET answer = excluded.answer, ts = excluded.ts
	`
	_, err := s.db.Exec(q, surveyID, answer, voter)
	return err
}
