package store

import (
	"database/sql"
	"errors"
	"fmt"
	"regexp"
	"strings"

	_ "github.com/duckdb/duckdb-go/v2"
)

type Store struct {
	db *sql.DB
}

// votes  — every recorded click. Upserted by (survey_id, voter).
// surveys — optional per-survey allowed-answer allowlist. Empty / row-absent
// means "open mode" (any slug-valid answer counts). Populated via the
// `make survey-create` target which writes through Quack with the same
// SURVEY_QUACK_TOKEN as `survey-reset`.
const schemaVotes = `
CREATE TABLE IF NOT EXISTS votes (
    ts        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    survey_id VARCHAR   NOT NULL,
    answer    VARCHAR   NOT NULL,
    voter     VARCHAR   NOT NULL,
    PRIMARY KEY (survey_id, voter)
);
`

const schemaSurveys = `
CREATE TABLE IF NOT EXISTS surveys (
    survey_id       VARCHAR   PRIMARY KEY,
    allowed_answers VARCHAR   NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
`

// tokenSafe restricts the Quack token to URL-safe base64 chars so we can
// interpolate it into SQL without escaping. The token is generated by the
// operator (base64 of /dev/urandom), so this is purely a defence-in-depth check.
var tokenSafe = regexp.MustCompile(`^[A-Za-z0-9+/=_-]+$`)

func Open(path, quackAddr, quackToken string) (*Store, error) {
	if !tokenSafe.MatchString(quackToken) {
		return nil, fmt.Errorf("SURVEY_QUACK_TOKEN must be URL-safe base64")
	}

	db, err := sql.Open("duckdb", path)
	if err != nil {
		return nil, err
	}
	// DuckDB has a single writer. Pin to one connection so writes and the
	// quack_serve call share the same session.
	db.SetMaxOpenConns(1)

	if _, err := db.Exec(schemaVotes); err != nil {
		return nil, fmt.Errorf("schema votes: %w", err)
	}
	if _, err := db.Exec(schemaSurveys); err != nil {
		return nil, fmt.Errorf("schema surveys: %w", err)
	}

	// Quack ships via the `core` extension repo from DuckDB 1.5.3 onwards.
	// Earlier versions (1.5.2 etc.) had it in `core_nightly` — this code requires
	// 1.5.3+, which is what duckdb-go-bindings/v2 v0.10503.x bundles for
	// linux/darwin/windows. The first `INSTALL` call needs outbound HTTPS to
	// extensions.duckdb.org to fetch the .duckdb_extension file.
	if _, err := db.Exec(`INSTALL quack`); err != nil {
		return nil, fmt.Errorf("install quack (need DuckDB 1.5.3+ and outbound HTTPS): %w", err)
	}
	if _, err := db.Exec(`LOAD quack`); err != nil {
		return nil, fmt.Errorf("load quack: %w", err)
	}

	// quack_serve takes named args via `=>`. The Go driver doesn't bind named
	// params, so we interpolate after validating both inputs above.
	quackURI := fmt.Sprintf("quack:%s", quackAddr)
	serveSQL := fmt.Sprintf(
		"CALL quack_serve('%s', token => '%s', allow_other_hostname => true)",
		quackURI, quackToken,
	)
	if _, err := db.Exec(serveSQL); err != nil {
		return nil, fmt.Errorf("quack_serve: %w", err)
	}

	return &Store{db: db}, nil
}

func (s *Store) Close() error { return s.db.Close() }

func (s *Store) RecordVote(surveyID, answer, voter string) error {
	const q = `
		INSERT INTO votes (survey_id, answer, voter) VALUES (?, ?, ?)
		ON CONFLICT (survey_id, voter) DO UPDATE
		SET answer = excluded.answer, ts = excluded.ts
	`
	_, err := s.db.Exec(q, surveyID, answer, voter)
	return err
}

// Tally is one (answer, count) pair for a survey. Ordered most-popular-first.
type Tally struct {
	Answer string
	Clicks int
}

// GetAllowedAnswers returns the per-survey answer allowlist as a set. A nil
// map means "the survey is not registered" — the vote handler treats that as
// open mode (any slug-valid answer counts). An empty (non-nil) map would
// mean "registered but allows nothing" — we don't expose that state, since
// the Makefile target rejects empty answer lists up-front.
func (s *Store) GetAllowedAnswers(surveyID string) (map[string]bool, error) {
	var raw string
	err := s.db.QueryRow(
		`SELECT allowed_answers FROM surveys WHERE survey_id = ?`,
		surveyID,
	).Scan(&raw)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	out := make(map[string]bool)
	for _, a := range strings.Split(raw, ",") {
		if a = strings.TrimSpace(a); a != "" {
			out[a] = true
		}
	}
	return out, nil
}

// TallyBySurvey returns the per-answer click count for a survey, most popular
// first. An unknown survey_id returns an empty slice (not an error) — the
// result page renders an "empty" state.
func (s *Store) TallyBySurvey(surveyID string) ([]Tally, error) {
	const q = `
		SELECT answer, count(*) AS clicks
		FROM votes
		WHERE survey_id = ?
		GROUP BY answer
		ORDER BY clicks DESC, answer
	`
	rows, err := s.db.Query(q, surveyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []Tally
	for rows.Next() {
		var t Tally
		if err := rows.Scan(&t.Answer, &t.Clicks); err != nil {
			return nil, err
		}
		out = append(out, t)
	}
	return out, rows.Err()
}
